### ISSUE TITLE
Pr.2: en la función proyectos estás haciendo PM anidado

### ISSUE THREAD

**Issue by Juan-Insa** [salvanescki/EstrD2023s1#11]
Fijate que acá el PM anidado te lleva a otro problema que es el PM innecesario. Esto pasa cuando pasas el constructor del lado izquierdo del igual ´=´ para el derecho, en este caso ConsEmpresa. 
Además, si usas subtareas, evitas hacer recursión sobre la empresa y estarías operando con la lista de roles, así vas delegando responsabilidades y la función proyecto no queda sobrecargada.

**Comment by salvanescki** [comment]
Listo

**Comment by Juan-Insa** [comment]
Bien, hay un detalle, en listaProyectosSinRepetir estás mirando la pertenencia contra una lista más larga de lo necesaria. 

Al usar pjs en lugar de sinReplistaProyectosSinRepetir pjs en la condición, mirás más veces de las necesarias.

Una mejor forma de resolverlo igual sería utilizar una subtarea, por ej, agregarSiNoEsta al que le pasarías el pj y la parte recursiva sinReplistaProyectosSinRepetir pjs, así quedaría mejor el esquema de RE.

**Comment by salvanescki** [comment]
Listo
