### ISSUE TITLE
Pr.2: la función cantQueTrabajanEn tiene demasiadas responsabilidades

### ISSUE THREAD

**Issue by Juan-Insa** [salvanescki/EstrD2023s1#13]
Mismo issue que en funciones anteriores

**Comment by salvanescki** [comment]
Listo

**Comment by Juan-Insa** [comment]
mismo detalle que la función anterior, en la subtarea cantEmpleadosTrabajandoEnProyectosEnListaRoles el segundo caso no es necesario.

**Comment by salvanescki** [comment]
Listo
