### ISSUE TITLE
Pr.2: la función asignadosPorProyecto recorre la empresa muchas veces

### ISSUE THREAD

**Issue by Juan-Insa** [salvanescki/EstrD2023s1#14]
Al querer reutilizar la función proyectos terminas recorriendo la empresa muchas para evitar los repetidos, y después, por cada proyecto, volver a recorrer todo para contar. Hay que pensar mejor la recursión.

**Comment by salvanescki** [comment]
Listo. En este caso, para evitar que la lista de pares resultante tenga repetidos, se los elimine con varias subtareas. El problema que me di cuenta, es que quizas haya una posibilidad de reutilizar las funciones de Proyecto que use para hacer básicamente lo mismo que con los pares. No se me ocurrio como hacerlo y si haskell me lo permite, si crees que puedo hacerlo después avisame y lo intento. Muchas gracias por todas las correcciones, me ayudaron un montón a entender que tenía mal y no marearme!

**Comment by Juan-Insa** [comment]
Sigue recorriendo muchas veces los proyectos de la empresa.
Yo lo que recomendaría es que no se recorran los proyectos junto con los roles. 

Sería mejor si cantEmpleadosAsignadosPorProyecto recorriera solamente los roles y siguiera el esquema de RE con ayuda de una subtarea. 
Una que, por ejemplo, tome el proyecto del rol actual y lo agregue a la parte recursiva (a lo Miyagi). 

Acordate como era, vos confiás en el resultado que te devuelve la parte recursiva que sería una lista de par (Proyecto, Int) a la que solo te quedaría agregar el primer elemento, en este caso el proyecto del rol actual, a la lista o en caso de ya estar, sumarle un integrante.

No se si me explique bien pero sería algo parecido a agregarSiNoEsta, la subtarea que te recomende hacer para listaProyectosSinRepetir. Creo que si te sale esa se hace más fácil de ver.

**Comment by salvanescki** [comment]
Listo
