### ISSUE TITLE
Pr.3: en hayTesoroEn podrías mejorar mucho usando una subtarea

### ISSUE THREAD

**Issue by Juan-Insa** [salvanescki/EstrD2023s1#25]
Fijate que estas mirando dos argumentos (PM) a la vez cuando analizas si n es cero con los constructores de camino. Pensá en n = 0 como un caso particular.

**Comment by salvanescki** [comment]
Listo

**Comment by salvanescki** [comment]
Me pasé de la entrega supongo, pero quiero entender el issue. El caso 0 es el último paso que se da, pero queda comprobar si en ese camino hay algun tesoro o no, me equivoco?

**Comment by salvanescki** [comment]
Mañana te pregunto en la clase igual, porque no me quedo muy claro que estoy haciendo/pensando mal

**Comment by Juan-Insa** [comment]
Perdona estaba viendo la versión vieja, el caso base esta bien, el problema ahora es que haces siguienteCamino cm, por lo que la función no está hecha estrictamente por recursión estructural. Tenes que hacerla con RE. Tranqui te banco hasta que lo cambies para cerrar la practica porque me atrase con las correcciones y además te queda solamente este issue.

**Comment by salvanescki** [comment]
Juan, ahi lo implementé con RE en la misma función, no puse el caso de Fin porque no lo había puesto cuando delegue subtarea, pero ahora estoy dudando

**Comment by Juan-Insa** [comment]
Tenés que poner el caso de Fin porque queda delegado a la subtarea sólo en el caso en que n es 0, entonces si quedan pasos y llegas a Fin explota todo.

**Comment by salvanescki** [comment]
Listo
