### ISSUE TITLE
Pr.3: alMenosNTesoros trabaja de más

### ISSUE THREAD

**Issue by Juan-Insa** [salvanescki/EstrD2023s1#26]
Estás reemplazando una búsqueda por una totalización, y eso no es bueno. Esto pasa porque al utilizar cantTesorosEnCamino terminas recorriendo todo el camino. La idea es que salga por RE

**Comment by salvanescki** [comment]
el primer commit que sale era para el issue #25 me equivoque al escribir el commit

**Comment by Juan-Insa** [comment]
Sigue siendo una totalización, recorres todo el camino para contar todos los tesoros y después lo comparas con n. La idea es cortar cuando ya tenés la respuesta con un short circuit utilizando operadores lógicos en la recursión. 
Acordate que lo vieron en InPr con la búsqueda del ancho de espadas: si tengo 10mil cartas, y el ancho está primero, si trato de contar los anchos tengo que mirar las 10mil cartas, pero puedo cortar apenas veo esa carta y no necesito mirarlas todas...

**Comment by Juan-Insa** [comment]
Bien, pero lo que devuelve el segundo caso es incorrecto. Asumiste que si el camino es Fin el resultado es falso cuando deberías estar analizando n.
