### ISSUE TITLE
Pr.2: En aplanar, es feliz usar nombre de listas para las listas

### ISSUE THREAD

**Issue by Juan-Insa** [salvanescki/EstrD2023s1#6]
Si un argumento tiene tipo [a] entonces es feliz llamarlo xs y no x (vendría de muchaS x). Esto permite identificar más fácilmente de qué va la función, sin necesidad de estar todo el tiempo haciendo saltos mentales.
Consecuentemente, si un argumento tiene tipo [[a]] lo llamamos xss (o sea, muchaS xs).

Es más que nada un tema de seguir la convención del lenguaje haskell.

**Comment by salvanescki** [comment]
Listo
